### PR TITLE
don't enforce /usr/local, allow variables being overwritten

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by rustybird** [comment]
`?=` is a GNUism, right? I don't know how well that would work with other `make` implementations. Why not use the conventional way to override Makefile variables:

    make PREFIX=/usr DESTDIR=/tmp/corridor install install-systemd

**Comment by adrelanos** [comment]
Rusty Bird:
> `?=` is a GNUism, right?

No idea. Never used a non-GNU make.

> I don't know how well that would work with other `make` implementations. Why not use the conventional way to override Makefile variables:
> 
>     make PREFIX=/usr DESTDIR=/tmp/corridor install install-systemd
> 

Because that doesn't work without ?=. Didn't work for me. Hence I
suggested the ?=. Looks like like just = sets the variable no matter
what the environment has set.

**Comment by rustybird** [comment]
>>     make PREFIX=/usr DESTDIR=/tmp/corridor install install-systemd

> Because that doesn't work without ?=

It definitely should. You probably have a mismatch between the `PREFIX` you are passing (or not) to one of the build targets vs. one of the install targets. (If it's a problem during testing, the build directory might be dirty.)

**Comment by adrelanos** [comment]
My mistake. It does.

**Pull request closed without merging**
